name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      #- name: Secret Scanning
      #  uses: gitleaks/gitleaks-action@v2
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Dependency Review
      #  uses: actions/dependency-review-action@v4
      #  with:
      #    base-ref: "${{ github.event_name == 'push' && github.event.before || '' }}"
      #    head-ref: "${{ github.event_name == 'push' && github.sha || '' }}"

      # TODO: Test with Semgrep as well

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
      
      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/lasselund-egmose/app-service-python-test/app-service-python-test:latest

      #- name: Build Docker Image
      #  run: |
      #    docker build -t app-service-python-test-${{ env.BRANCH_NAME }} .

      # TODO: Maybe a security gate could be added here as well?

      - name: Azure Deploy
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/lasselund-egmose/app-service-python-test/app-service-python-test:latest